apiVersion: v1
kind: Pod
metadata:
  name: model-training
spec:
  containers:
    - name: model-training
      image: model-training:latest
      imagePullPolicy: Never
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: shared-data
          mountPath: /app/data
  volumes:
    - name: shared-data
      hostPath:
        path: /data
        type: DirectoryOrCreate