apiVersion: batch/v1
kind: Job
metadata:
  name: data-fetch
spec:
  template:
    metadata:
      name: data-fetch
    spec:
      containers:
        - name: data-fetch
          image: data-fetch:latest
          imagePullPolicy: Never
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-database-cluster-app
                  key: username
                  optional: false
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: my-database-cluster-app
                  key: password
                  optional: false
            - name: DB_HOST
              value: my-database-cluster-rw
            - name: DB_NAME
              value: app
            - name: CSV_PATH
              value: /app/AutoInsuranceClaim.csv
            - name: N_ROWS
              value: "100"
      restartPolicy: Never
  backoffLimit: 1