apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: full-pipeline-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This workflow runs the whole e2e pipeline.
spec:
  entrypoint: full-pipeline
  volumes:
  - name: shared-data
    hostPath:
      path: /data
      type: DirectoryOrCreate

  templates:
    - name: full-pipeline
      steps:
        - - name: data-fetch
            template: data-fetch
            arguments:
              parameters:
                - name: n_rows
                  value: "100"
        - - name: preprocessing
            template: preprocessing
        - - name: model-training
            template: model-training

    - name: data-fetch
      inputs:
        parameters:
          - name: n_rows
      container:
        image: data-fetch:latest
        imagePullPolicy: Never
        command: [python]
        args: ["fetch.py"]
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: my-database-cluster-app
                key: username
                optional: false
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: my-database-cluster-app
                key: password
                optional: false
          - name: DB_HOST
            value: my-database-cluster-rw
          - name: DB_NAME
            value: app
          - name: CSV_PATH
            value: /app/AutoInsuranceClaim.csv
          - name: N_ROWS
            value: "{{inputs.parameters.n_rows}}"