apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - data-fetch-pipeline.yaml
  - full-pipeline.yaml
  - train-and-deploy-pipeline.yaml
  name: pipelines-conf