apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: scheduler-cron
spec:
  schedule: "*/5 * * * *" # every 5 minutes
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0

  workFlowSpec:
    entrypoint: full-pipeline
    volumes:
    - name: shared-data
      hostPath:
        path: /data
        type: DirectoryOrCreate
    - name: pipelines
      configMap:
        name: pipelines-conf-47b2m7kc6t
    
    templates:
      - name: full-pipeline
        steps:
          - - name: scheduler
              template: scheduler

      - name: scheduler
        container:
          image: scheduler:latest
          command: [python]
          args: ["scheduler.py"]
          imagePullPolicy: Never
          env:
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: default.service-account-token
                  key: token
                  optional: false
            - name: HOST
              value: argo-server.argo
            - name: PIPELINE_PATH
              value: /app/pipelines/train-and-deploy-pipeline.yaml
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-database-cluster-app
                  key: username
                  optional: false
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: my-database-cluster-app
                  key: password
                  optional: false
            - name: ELECTRICITY_MAPS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: electricity-maps-token
                  key: token
                  optional: false
            - name: DB_HOST
              value: my-database-cluster-rw
            - name: DB_NAME
              value: app
            - name: MODEL_FILE_PATH
              value: /app/data
            - name: MAX_ACCURACY_DECREASE
              value: "0.05"
            - name: LOW_ACCURACY_DECREASE
              value: "0.0"
            - name: CARBON_INTENSITY_THRESHOLD
              value: "600"
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
            - name: pipelines
              mountPath: /app/pipelines